#!/usr/bin/env bash
# Transfers file

path="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
filename=$(basename "$0")
brown='\e[0;33m'
reset='\033[0m'
file="$1"
ip="$2"
user="$3"
key="$4"

if [ $# -eq 4 ]; then
    if [ -f "$file" ]; then
        scp -i "$key" -o StrictHostKeyChecking=no "$file" "$user"@"$ip":/home/"$user"/
        echo "File transferred successfully to $user@$ip:/home/$user/"
    else
        echo "Error: File $file not found."
        echo -e "Usage: ${brown}$filename PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY${reset}"
        exit 1
    fi
else
    echo -e "Usage: ${brown}$filename PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY${reset}"
    exit 1
fi