#!/usr/bin/env bash
# setup nginx
c1='\e[0m'
c2='\e[103m'
c3='\e[1;32m'
c4='\e[31m'
echo -e "${c1}Updating and installing ${c2}Nginx${c1}.${c4}\n"
sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y
echo -e "\n${c1}Setting up some minor stuff.${c4}\n"
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo service nginx restart
echo -e "\n${c3}done.${c4}\n"
