#!/usr/bin/env bash
# install haproxy
set -e
if ! command -v haproxy &> /dev/null; then
    sudo apt-get install -y haproxy
else
    echo "HAProxy is already installed."
fi
cat <<EOT | sudo tee /etc/haproxy/haproxy.cfg
frontend qubitket.tech
    timeout client  30000
    bind 0:80
    default_backend qubitket.tech_backend

backend qubitket.tech_backend
    timeout connect  3000
    timeout server  30000
    balance roundrobin
    server 238549-web-01 100.27.0.247:80 check
    server 238549-web-02 100.26.162.119:80 check
EOT
sudo haproxy -c -f /etc/haproxy/haproxy.cfg && sudo service haproxy restart
set +e
